### ISSUE TITLE
Water level screw-up after setting the markers

### ISSUE THREAD

**Issue by tobiassiegfried** [luethi/Discharge_Optical_Measurement#11]
see screenshot attached... reproducible for Vatok and Wildbach 1a sites (for which I have tested the new app)...

![screenshot_20160915-163529](https://cloud.githubusercontent.com/assets/9135339/18554481/b4885532-7b64-11e6-97e7-7832020a8700.png)

**Comment by tobiassiegfried** [comment]
I should say that the water level is always indicated from the top left going down to the lower right corner... (see attachment above) and the slider does not work...

**Comment by luethi** [comment]
I will go tomorrow to letten free to see for myself

**Comment by tobiassiegfried** [comment]
will go to letten myself in a couple of minutes to check (passing by there) - but please try Vatok! me no work anymore, and also Wildbach 1a...

**Comment by salpeha** [comment]
Ranko mentioned that we should uninstall the old version. I did that and all my videos are gone. How are you processing Vatok? I guess you didn't uninstall, wonder if that is the reason. We should try with a freshly taken video.

**Comment by tobiassiegfried** [comment]
I uninstalled the old version first.. Vatok was still there...

**Comment by luethi** [comment]
Tobi dear, 
My vatok is also gone. But I know how to get it back.
Independent of that... have you REALLY actually succeeded to fake measure a vatok from a beamed to the wall image. ..?? I am asking because I realized that this should not work in theory: the phone orientation will be wrong,  hence all that follows will be Chabis...

**Comment by tobiassiegfried** [comment]
Haha, Chabis! Maybe :) - but seriously, Wildbach 1a filmed from the screen
- Chabis water level... Vatok film still in the app (yes, believe me, I
  downloaded RC4 from the App Store after uninstallstion of the previous
  version, so still in the app with just pressing the process button - Chabis
  water level in the same way as Wildbach 1a before... now, Letten free a
  couple of Hours ago ( though markers are all but gone) - all good - I am
  lost :)

**Comment by luethi** [comment]
I close this ticket, I think it is solved, and there has been a new release.
