### ISSUE TITLE
Rating Curve

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#13]
when setting one or more rating curves for a site, what is the way to define one of them as the "master"one? what I mean is how to define a rating curve which will be used to calculate discharge directly from a picture (without having to process the video)?

*Just to clarify, I see the "set as primary" function, but even when that is clicked, I don't get a discharge from a single photo.

Thanks,
Phanos

**Comment by luethi** [comment]
Hi Phanosh,
you will, the Croatiens are working on it, that you don't see it already is a bug. What works for sure is Q-h rating curves set as primary. I will talk also to this in 1min from now with Lovre

**Comment by luethi** [comment]
the guys have fixed it and in the next release we will see it

**Comment by phanosh** [comment]
perfect thanks!
