### ISSUE TITLE
Indicator when data has not yet been uploaded

### ISSUE THREAD

**Issue by julesair** [luethi/Discharge_Optical_Measurement#15]
There is no clear indicator for data, which has not yet been uploaded because their was no internet/sms connection on the site. In fact, the icon in the menu "examine data" is the same as for data which is already online. So you have to click on the upload icon for every data point to be sure that everythin is online or remember the time when the new measurement was taken. It is not a big deal, but having two different icons for the two situations would make it clear. 
(see the Screenshot for what icon is meant)
![screenshot_2016-09-29-14-31-28](https://cloud.githubusercontent.com/assets/11719541/18952272/5051faf6-8649-11e6-96a6-ce20b2e6dc8b.png)

**Comment by luethi** [comment]
Hi Jule,
first of all: YOU ARE GREAT!! This just completed a huge milestone. Somebody other than me or Salvador actually made a real site. Now to your question. Actually I don't get it. When I measure, I always have a cloud with, a) and upwars arrow or b) a checkmark. (c) during uplaoding I see 3 dots). But when you say there was no internet or sms on site... Are you saying you immediately got the checkmark? I don't think I can reproduce this behaviour?

**Comment by julesair** [comment]
Hey Beat,
Thanks! Actually the Pangani Basin Staff did it (with some support from our side ;-) )

To be honest, I can not reproduce this behavior anymore either. Maybe I just confused the icons. I will check again next time I do offline measurements. 

Nevertheless, a good thing to include in a future version of the app would be 
- to include an "upload all" button somewhere or have a setting to activate automatic uploads as soon as there is a internet connection, so one does not have to search for all the offline measurements. 
- to mark the offline measurements in the list of measurement. Than one would not have to cklick on the measurement to see if it is online or offline.
