### ISSUE TITLE
Deleting measurements on dischrage.ch

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#16]
How can a user (considering he has all rights over a site) delete measurements taken at that site? I am referring to measurements that any user has uploaded (e.g. in case of error).

Thanks, 
Phanos

**Comment by luethi** [comment]
actually he cannot, by design. It is like shooting a gun. you can't stick the bullet back in. However, there is the possibility that data can be validated. Default is: don't need to be validated.

**Comment by phanosh** [comment]
Ok, thanks. We were thinking that the admin or "head" of a certain organization should maye have the ability to delete some measurements. since the crowd senders will often be non-professionals, there is the possibility of wrong data uploaded. Is that something feasible?

**Comment by luethi** [comment]
That is what we want to use the validation feature. My opinion is: that every submitted measurement should leave it's trace. 
But of course, this is just my opinion. Let's see how it develops , technical we would fine a solution I guess

**Comment by bosnjak** [comment]
There will be a middle ground definitely, but no one will be able to actually delete a measurement. What they will be able to do (if they have the right permissions) is to mark them as "Rejected" - thus removing them from production data. They will still be used as metrics for other purposes like statistics etc. This feature is not prioritized in the next few weeks, but will be available in a reasonable time frame.

**Comment by luethi** [comment]
Hi Lovre , 
At some point we should continue our discussion on this. Let's do it on Tuesday

**Comment by bosnjak** [comment]
Sure!
