### ISSUE TITLE
Mabogini in right organization?

### ISSUE THREAD

**Issue by luethi** [luethi/Discharge_Optical_Measurement#17]
Guys are you sure that e.g. Mabogingi furrow belongs Pangani Official Sites? Should it not be Themi Catchment?
Oh well, you will know, let me know if you want to change, but can't.

**Comment by phanosh** [comment]
Hello Beat, 
You are right that they're not really "Official Sites of Pangani" but since they were set as an example and control for the PBWO team on how to set new sites, it is better if they stay under that organization and not under Themi catchment.

Thanks, 
Phanos

**Comment by luethi** [comment]
fair enough!
