### ISSUE TITLE
Primary rating curve defined on dischsarge.ch does not appear on the app, and discharge cannot be calulated

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#18]
When setting a rating curve on discharge.ch as the primary one, in theory it should be visible on the app "Collect" function. However, quadratic curves are not visible and none of the sites we've tried it on seem to work. This means that we enter a water level value but do not get a discharge out of it.

**Comment by luethi** [comment]
Dear Lovre and Ranko, 
Please, can we once and for all have the quadratic rating curve not showing issue cleared? Compared to all the other things,  this one seems so trivial. I fail to understand why this issue is so persistent? Can we move it to pool position on the priority list?

**Comment by bosnjak** [comment]
Resolved via: https://github.com/luethi/discharge/issues/149
