### ISSUE TITLE
Little issue while adding a new site to an organisation. 

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#2]
Hello Team,
The text in the box to add a new site to an organisation is not shown properly. 
<img width="595" alt="screen shot 2016-09-08 at 09 36 59" src="https://cloud.githubusercontent.com/assets/21307977/18341172/0a785bb6-75a9-11e6-964c-864de60be328.png">

Regards robert

**Comment by luethi** [comment]
I assume this is resoleved, I close this ticket.
