### ISSUE TITLE
Non-urgent sugestions --> Process later & Upload all buttons

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#21]
I know there's a lot on your table right now, so these are suggestions for the near future to improve user experience. 
1. It would be nice if after taking a video, the user gets a window asking  whether to process now or later. Although it's totally possible to just go back and take other measurements right now too, it's not very intuitive. This would be especially useful for a crowd sender which has to (or wants to) measure several sites every day. We've noticed in the field that most phones take 5 minutes or more to process a video. 
2. Additionally, It would be nice to have an "upload all" button. When having processed several videos, one has to go through "Examine Data" on each site and click on recent measurements to see whether they are uploaded. Having such a button ("upload all") would make it more efficient and reduce the work for the user.

**Comment by luethi** [comment]
These are very good inputs , I just created an asana task https://app.asana.com/0/168268173031468/107360540007844
