### ISSUE TITLE
2. Priority Issue: Using Rating Curve the other way around

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#22]
The scheme management in Uganda suggests to use the H-Q relation on the App in a way to adjust the gates at secondary canals to get a certain flow. Meaning that it should be possible to tipe-in the required flow [l/s] in order to know which water-level [cm] he should have in the canal. But before this the other issue concerning H-Q relationship should be addressed.

**Comment by luethi** [comment]
Hi RObert, so I let you close this, if you think the way I showed to you yesterday is enough for now?

**Comment by naroberto** [comment]
Yeah I think it's fine :)
