### ISSUE TITLE
Show more then two digits on discharge.ch as e.g 0.007 m3/s are displayed as 0.00 discharge...

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#23]
<img width="483" alt="screen shot 2016-11-03 at 11 28 02" src="https://cloud.githubusercontent.com/assets/21307977/19962661/0b4cbe4c-a1b9-11e6-9fac-d91815f9e46b.png">
<img width="125" alt="screen shot 2016-11-03 at 11 28 20" src="https://cloud.githubusercontent.com/assets/21307977/19962662/0b4e7e12-a1b9-11e6-88f3-e2bd3a95e989.png">
<img width="1242" alt="screen shot 2016-11-03 at 11 32 48" src="https://cloud.githubusercontent.com/assets/21307977/19962727/4ac409d6-a1b9-11e6-94b6-deda0149c298.png">

**Comment by naroberto** [comment]
Also the same issue with time shift of one hour appears here...

**Comment by bosnjak** [comment]
Hi @naroberto, thanks for reporting.
The precision of 3 digits for measurement seems rather too fine for this purpose, don't you think? Should we go about this by rounding to 2 digits, so in this case we would have 0.01 as a result? @luethi what's your opinion on this? For a system that has a large toleration margin, 3 digits just seems as overkill.

@naroberto about the time shift: the time in the exported CSV is in UTC, and the time you see on the frontend is in your local timezone. I suspect you are in Zurich now? Or at least in the CET zone, which would put you in UTC+1. I hope this helps.

**Comment by naroberto** [comment]
Hmm not sure because the discharge really varies a lot from site to site. For low discharge the relative error introduced by displaying it like this is very high and looks confusing because 4 l/s will be displayed as zero discharge as in fact 4 l/s or lower occurs sometimes. E.g at Seliani River Sites the discharge is often in the margin of 4-8 l/s (or 0.004-0-008 m3/s) and especially if you round 0.004 down to 0.00 it doesn't look meaningful anymore... of course the real value is still visible when you download the data, but I think something meaningful should also be visible when you click on the web...
<img width="497" alt="screen shot 2016-11-03 at 11 57 02" src="https://cloud.githubusercontent.com/assets/21307977/19963583/60c0f48e-a1bd-11e6-97be-815534d08eab.png">

**Comment by bosnjak** [comment]
@naroberto right, I didn't think about it like that, I was thinking in terms of much higher flows, but you are right - we definitely need to account for these low flow measurements.
@luethi: should we display m3/s when the number is high, and then just switch to L/s when the number is this low? To me it seems better to show 2 L/s than having 0.001 m3/s. What do you guys think?

**Comment by naroberto** [comment]
Yes I think that would be great and the App is actually already switching to display the result... But it might still be inconvenient if you download a long time series of a site and some discharge is in m3/s and some are in l/s... So for one site measurements should either be in m3/s or in l/s...

**Comment by bosnjak** [comment]
Can we then agree that the exported data will always be in m3/s, and on the fronted interface we will display m3/s or L/s depending on the value? This makes sense to me because the frontend should be user-friendly, and the export should be machine-friendly.

**Comment by naroberto** [comment]
Yes, if that's possible - perfect!

**Comment by bosnjak** [comment]
I've created the ticket on the frontend backlog: https://github.com/luethi/discharge_web_frontend/issues/223

@naroberto if this addresses your concerns, please close this ticket. Thanks!
