### ISSUE TITLE
Discharge Site Down?

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#24]
Hello, 

I'm trying to access the site but I get a message saying the site cannot be reached.

**Comment by bosnjak** [comment]
Hi @phanosh, we're working on it, the site will be back online shortly.
Sorry for the inconvenience, we are undergoing some major refactoring on the backend which will be released very soon. In parallel we will use a more powerful instance, so these things won't happen anymore. 
Thanks for reporting!

**Comment by phanosh** [comment]
no problem! Thanks for the answer

**Comment by phanosh** [comment]
@bosnj : There are some sites which give the message "Error getting measurements" and I can't see any of the data for them. 
An example is Ngaramtoni River under "Themi Catchment" organization

**Comment by bosnjak** [comment]
@phanosh I've just checked and it seems to work for me. Can you try reloading the site please?

**Comment by phanosh** [comment]
@bosnj : Still the same  issue.. The window on the right starts loading and then disappears before I can read any data. This also happens for Asa furrow, Kichangani furrow and Kigongoni furrow,

**Comment by bosnjak** [comment]
@phanosh I can see now that for your user there is some issue. We're looking into it, will get back to you asap.

**Comment by phanosh** [comment]
Ok thanks. FIY, we also tried with Jules' account and there is the same issue.

**Comment by bosnjak** [comment]
@phanosh we have identified the issue, and are working to fix it. In the meantime, I've fixed it for you and Jules, can you please verify that it's now working?

**Comment by phanosh** [comment]
@bosnj : Yes it works!

**Comment by bosnjak** [comment]
Great! You can close this ticket now.
