### ISSUE TITLE
Error when trying to add site to an organization

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#25]
As described in the title, I get an error: "Error. Cannot add site" 

Is is a rights issue?

**Comment by bosnjak** [comment]
Thanks for reporting @phanosh. Can you please tell me which Organization did you try to add a site to?

**Comment by phanosh** [comment]
No problem. The organization is Costa Rica and the site is just called New Site (under Open World right now). There's 2 sites with that name in the same location.

**Comment by bosnjak** [comment]
I've moved both sites to Costa Rica organization for you. You couldn't do it because you don't have permissions to manage sites in Open World. This is normal, but the error message should have been more clear about that. We will improve it.
Thanks!

**Comment by bosnjak** [comment]
@phanosh can you please close this ticket? Thank you!
