### ISSUE TITLE
kst values in discharge app

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#26]
Dear Beat,
this is Timo, a new intern at hydrosolutions ltd.!
We just set up a site with the new 1.2.0 version of discharge. We found it somehow inconvenient, that kst values need to be checked on the webplatform, as there is not always a laptop available when people are setting up a new site in the field. We would prefer to have the kst values either in the app manual or directly in the app, with a similar information button as on the web platform, popping up the values.

Looking forward to your answer,
kind regards,
Timo

**Comment by bosnjak** [comment]
@timoherberz we have added kst values inside the mobile app as well. You should be able to see it in the next release, which will happen next week.

**Comment by bosnjak** [comment]
@timoherberz I believe it is ok to close this ticket now, since kst values are available in the app.
