### ISSUE TITLE
Author: N/A on discharge.ch

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#28]
Dear Beat,
we set up a new dummy site called "Wildbach_Timo" in the organisation "Open World". After taking the first measurements, we saw, that the author of the measurements was not indicated on discharge.ch. Actually it should show the user name of the person who was logged in during taking the measurements, right?

Kinds regards,
Timo

**Comment by bosnjak** [comment]
Hi @timoherberz, this is what I see on the site:

![image](https://cloud.githubusercontent.com/assets/10396664/22735786/96d95e8c-edfb-11e6-8f9c-03add10edf6a.png)

It seems ok, or am I missing something?

**Comment by timoherberz** [comment]
Hi!

This is what I see, even though I have all the administrative rights for 
the organisation. I also crosschecked with Robert Naudascher wo created 
the organisation.

Kind regards,
Timo

Am 08.02.2017 um 12:39 schrieb bosnj:

**Comment by bosnjak** [comment]
I'm not following. Are you saying that you also see "timoherberz" user as the author for all the measurements? What are you expecting to see?

**Comment by timoherberz** [comment]
Sorry, the attached file didn't load up...

**Comment by timoherberz** [comment]
![screenshot 08 02 2017](https://cloud.githubusercontent.com/assets/25477472/22736974/53ff50f2-ee01-11e6-8509-0c7c3ee5251f.jpg)

**Comment by bosnjak** [comment]
I can't seem to find Wildbach_Timo anymore, have you renamed or moved it?

**Comment by timoherberz** [comment]
Yes, sorry! We added it to a new organisation called Rufiji Basin. My bad.

Am 08.02.2017 um 13:24 schrieb bosnj:

**Comment by bosnjak** [comment]
@timoherberz so is it working now when in new organization, or do you still see N/A?

**Comment by timoherberz** [comment]
I still see N/A.

Am 08.02.2017 um 17:21 schrieb bosnj:

**Comment by bosnjak** [comment]
@timoherberz just to inform you that this was a bug and has now been fixed.
It is still not available on production version, so you should see this fixed some time next week when we release the new version.
Thanks for reporting and for your patience!

**Comment by timoherberz** [comment]
Dear Bosnj,
I just wanted to report, that even after the release yesterday I am still experiencing the N/A problem.
Warm regards,
Timo

![screenshot 01 03 17](https://cloud.githubusercontent.com/assets/25477472/23471229/abfb3262-feb9-11e6-971c-4654470070f0.png)

**Comment by bosnjak** [comment]
Dear @timoherberz, can you please check now? We had a bit more delay for releasing this fix, but it should be fine now. Please confirm.

**Comment by timoherberz** [comment]
It is perfect now. Thank you!

Am 02.03.2017 um 12:29 schrieb bosnj:

**Comment by bosnjak** [comment]
Glad to hear @timoherberz. You can close this ticket now. Thanks!
