### ISSUE TITLE
Marker coordinates

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#3]
It's unclear what the purpose of the "Marker Coordinates" is. Should it not have 4 lines (to input 4 coordinate points)? 
Also, can the coordinate distances not be saved? when trying to test some values, the "update" button cannot be clicked.

**Comment by salpeha** [comment]
In "Markers Coordinates" you can introduce the x,y,z coordinates for each markers according to the following format: x1,x2,..,xn,y1,y2,..,yn,z1,z2,..zn
If you cannot click the "update" button (it is gray) it means that there is an error on the format.
