### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#30]
Hello,

I am trying to log in to discharge.ch, but it tells me, my password was wrong. Same happens to Robert N. We both saved our password in the browser, so there is no possibility, that the password is wrong. There must be an issue with the platform.

Thanks in advance,
Timo

**Comment by timoherberz** [comment]
The discharge app tells me as well, that it is not able to reach the server...

**Comment by salpeha** [comment]
I also have the same issue, I will contact Lovre

**Comment by salpeha** [comment]
@timoherberz it is solved
