### ISSUE TITLE
Rating curve on discharge.ch not visible on the graph

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#31]
Hello,

for the site Kikuletwa TPC in the organisation Official Sites Pangani, we received an official rating curve from the Pangani Basin Water Office. We inserted this curve into discharge.ch. But, when it is chosen to be visible, it doesn't show properly on the graph. When you follow the rating curve with the mouse, it shows the different points of the graph, but it doesn't show any line connecting these points.

Thanks in advance!

Kind regards,
Timo

**Comment by salpeha** [comment]
Hi Timo, I just see a rating curve called "RC-1"

**Comment by timoherberz** [comment]
Sorry, we moved the rating curve into a seperate site called "RatingCurvePBWO" in the sub-organisation "Kikuletwa@TPC" in the organisation "Official Sites Pangani".

**Comment by bosnjak** [comment]
@timoherberz: if this issue is resolved, we can close the ticket?
