### ISSUE TITLE
Sites discharge.ch are not identical in the organisation Themi Catchment

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#36]
Dear all, 
We have an issue in the organisation "Themi catchment". Sites on the App and on discharge.ch are not identical. 
Synchronising does not help. The site was setup in october last year and was already on discharge.ch as we entered the marker geometries there...

Discharge.ch:
<img width="1035" alt="screen shot 2017-02-27 at 16 33 07" src="https://cloud.githubusercontent.com/assets/21307977/23363758/452d9730-fd0d-11e6-9aee-090ca9d7d878.png">

On the App:
![screenshot_2017-02-27-16-34-41](https://cloud.githubusercontent.com/assets/21307977/23363764/54eb0bee-fd0d-11e6-9ad0-9b253eb89971.png)

**Comment by bosnjak** [comment]
Hi @naroberto, 

we have checked in our logs, and it seems that @luethi has removed those two sites from this organization on 06.Feb.2017. at 11:15 am.
@luethi did you do this on purpose or was it a mistake?

We can move those sites back to the organization if you wish, but let's understand first what @luethi was trying to do.
If you were indeed trying to remove them, then we have a bug on the mobile app which is not properly refreshed in such a case.

Cheers!

**Comment by bosnjak** [comment]
@naroberto, @luethi we have looked into this deeper, and it seems there is a bug on our side causing those site to be visible on the mobile app still. We have created a ticket to fix this:
https://github.com/luethi/discharge_web_backend/issues/439.

Nevertheless, can you confirm that you wanted to remove those two sites please?

**Comment by bosnjak** [comment]
@naroberto this should have been fixed now, with the new release made today. Can you please update the mobile app and verify that the issue is fixed? Thanks!

**Comment by naroberto** [comment]
Dear all, 
The sites should not be removed. They contain site specific data. 
Thanks I will try the new release 
Best Robert

**Comment by bosnjak** [comment]
@naroberto the sites are visible in the "Themi Downstream" organization. Please provide feedback here if everything is ok now.

@luethi: your feedback would also be valuable to understand what happened here. 

Thanks!

**Comment by naroberto** [comment]
@bosnj: Now the sites are not visible anymore. Not on the App and neither on discharge.ch. But we need them.
Is there a way to recover them?
Thanks and best 
Robert

**Comment by bosnjak** [comment]
@naroberto: as I said, the sites exist, but have been moved to a suborganization "Themi Downstream" under "Themi Catchment". You were not added to this organization, and I have added you now. Can you please check and confirm all is good now?

**Comment by naroberto** [comment]
Ah, ok,
Yes all is good now!
I will close this issue.

**Comment by timoherberz** [comment]
Is it possible to reopen this issue?

**Comment by timoherberz** [comment]
I just opened a new issue referring to this one here!
