### ISSUE TITLE
Export data from discharge.ch

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#37]
Dear all,
while presenting discharge.ch to the Rufiji Basin Water Office today, we experienced difficulties while exporting data from discharge.ch. We tried this for the site Ruaha at Mbuyuni in the organisation Rufiji Basin. The only data, we could download was the .csv-file. But even this file, once downloaded did not give any reasonable result, when opened in Excel.

How does data need to be exported in order to use it with Microsoft Excel?

Warm regards,
Timo

**Comment by bosnjak** [comment]
Thanks for reporting @timoherberz, we are on it. We will get back to you when it's fixed. Sorry for the inconvenience!

**Comment by timoherberz** [comment]
Hello Bosnj,
I managed now to export a .csv-file and to display it correctly with the right settings when opening with Microsoft Excel.

There is still a quite long delay (~1 minute) between clicking the "Export" button and the start of the download.
Of course it would be more convenient for our partners to export the .xls-file, as they are used to this format - but for now we will explain how it works with .csv

Kind regards,
Timo

**Comment by bosnjak** [comment]
Hi @timoherberz,

I believe all formats should be working normally now. Can you please check and confirm? Thanks!

**Comment by timoherberz** [comment]
Hi bosnj,
yes, I can confirm, .xls is also working now!
Just a proposal from the hydrologists here: For them it would be more natural, if the discharge is written in the rightmost column, but it's of couse not an issue to do this manually.

**Comment by bosnjak** [comment]
@timoherberz can we close this one then? Thanks!
