### ISSUE TITLE
Shapefiles in discharge.ch

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#38]
Dear all,
today one of the hydrologists from Rufiji Basin Water Office asked, whether it is possible to insert shapefiles into the map used by discharge.ch. I told him, that I didn't know any possibility but found that the idea is an interesting one. Maybe you can give us a feedback on the feasibility of such a feature and how you like the idea.

Warm regards,
Timo

**Comment by bosnjak** [comment]
Hi @timoherberz, thanks for reporting. The idea is solid, but we have a similar idea reported a while ago by Robert: https://app.asana.com/0/search/283009517380216/193191835599430
Is that the same, or different? I'm not too familiar with KML and shapefiles..

**Comment by timoherberz** [comment]
Yes, looks as if it is/was the same idea. Thanks! As far as I know KML and shapefiles are the same.

**Comment by bosnjak** [comment]
@timoherberz maybe we can close this ticket then, since the idea is in our Asana backlog?
