### ISSUE TITLE
Problem with synchronization between app and discharge.ch

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#39]
Dear all,
this issue is similar to "Sites discharge.ch are not identical in the organisation Themi Catchment" that Robert created.

On discharge.ch the site Highland estates intake is in the sub-organisation "Highland Estates Limited"
In the app the site Highland estates intake is in the organisation Rufiji Basin and the sub-organisation is empty.
Please check the following screenshots:
![screenshot_2017-03-01-20-12-41](https://cloud.githubusercontent.com/assets/25477472/23472033/8d95c410-febc-11e6-9a91-e73e6dd3c96b.png)
![screenshot_2017-03-01-20-12-54](https://cloud.githubusercontent.com/assets/25477472/23472034/8d9a2a5a-febc-11e6-8211-604e9549332a.png)
![screenshot 01 03 17](https://cloud.githubusercontent.com/assets/25477472/23472035/8d9dd4b6-febc-11e6-952e-12660ac72207.png)
![screenshot 01 03 17 2](https://cloud.githubusercontent.com/assets/25477472/23472036/8db682c2-febc-11e6-806d-59fb8a8495c6.png)

**Comment by timoherberz** [comment]
(I guess) due to this error the oploading of videos to the cloud (sending debug data) also fails for this site.

**Comment by bosnjak** [comment]
Thanks for reporting @timoherberz, we're on it. Will report back shortly.

**Comment by bosnjak** [comment]
Hi @timoherberz, I see this ticket is still open, but the issue was resolved a few weeks back. Can you please verify that the problem is gone, and close the ticket? Thanks!
