### ISSUE TITLE
Multiple sites created

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#41]
Dear all,
when we create a new site in the field, we always have the problem that multiple sites with the same name are created. It happens especially when network is bad. The response from the cloud is that it was not possible to upload the site, but actually it is already uploaded. When clicking again the upload button in the app, an identical site is created on discharge.ch.

![screenshot 08 03](https://cloud.githubusercontent.com/assets/25477472/23721243/3758f662-0452-11e7-857f-2ddbc8ec52b1.png)

**Comment by rmunk** [comment]
Thank you for reporting this issue. It has been fixed here: https://github.com/luethi/discharge/issues/262. Fix will be available with the next application update.

**Comment by timoherberz** [comment]
Alright, thanks!
