### ISSUE TITLE
Processing failed

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#42]
We experienced issues at the site "Mlowo @ Inyala A intake", which is in the organisation "Rufiji Basin".
On the 20th of March I uploaded several videos from the account of "abelmaganga22".
For some of them processing failed and I couldn't tell why. The conditions seemed good to me.
What was the problem? How can we avoid it?

Kind regards,
Timo

**Comment by bosnjak** [comment]
@TPhilippe can you take a look please?

**Comment by bosnjak** [comment]
obsolete
