### ISSUE TITLE
 User doesn't belong to any organisation

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#44]
Dear all,
I saw that there is a new option to chose the public organisations you want to join when creating a discharge account.
This happened, when I tried to create a new account on the phone for one of our crowd-senders on 22th of March:
- I created the account with the discharge app
- I was not asked which public organisations I want to join
- When trying to log in, I was told that the user doesn't belong to any organisation and thus cannot be logged in

I found this confusing, but managed to solve the problem by adding the user manually to an organisation.
Is it on purpose that the option to join public organisations only appears when you create a new account on discharge.ch, but not when creating with the app?

Kind regards,
Timo

**Comment by rmunk** [comment]
Hi Timo,

Do you know what app version were you using then. If you haven't updated the app to latest version 1.3.1 at the time than this is exactly what would have happened after 21st of March. In the latest version after you create a new account you are taken to the screen where you must pick one or more public organizations to join before proceeding further.

Best regards,
Ranko

**Comment by timoherberz** [comment]
Dear Ranko,
I have to admit that I don't know, which version I was running that day. But most probably the missing update was the reason for the difficulties I had. Thanks for clearifying!
I will close this issue.
