### ISSUE TITLE
Data disappeared from the phone

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#45]
Dear all,
after installing the update from 21st of March all the previous measurements disappeared from my phone. When I go to measurements, there is nothing left. It would be nice, if I could access these measurements even after the update. Also when solving issues with crowd-senders it is important to see all the measurements he/she has taken. Was this a feature of the update?

Kind regards,
Timo

**Comment by rmunk** [comment]
Dear Timo,

there was nothing in that update that should have effected your measurements. Are you sure you are logged in as same user and have right organization and site selected? If so, can you please check if measurements are still present on your phone. They should be located in the device storage folder:
_Android/data/ch.photrack.discharge/files/Movies_.

Also it would help me to investigate this issue if you can send me your `discharge.db` file located in _Android/data/ch.photrack.discharge/files_ folder.

Best regards,
Ranko

**Comment by timoherberz** [comment]
Dear Ranko,
yes, I am sure that I am logged in as the same user. I checked in the folder "Android/data/ch.photrack.discharge/files/Movies" and measurements are still present:
![screenshot_2017-04-03-10-43-04](https://cloud.githubusercontent.com/assets/25477472/24601765/7c1d5cae-185a-11e7-80e2-a058b813b790.png)

I sent you the discharge.db file via mail, since the data type is not supported by github.

Best regards,
Timo

**Comment by rmunk** [comment]
Dear Timo,

I have checked the database file you sent me and unfortunately there are only measurements made after 21st of March present in there. I must admit I am very much puzzled how this could have happened. Nobody else reported anything similar happening so far. Do you remember if anything unordinary happened during the update?

We are considering a way to allow users to download their uploaded measurements from the cloud to the phone so they can restore them if something similar happens. Please leave the movie files on the phone for now so when this new feature is ready you can restore these lost measurements.

Sorry I couldn't be much more help for now.

Best regards,
Ranko

**Comment by timoherberz** [comment]
Dear Ranko,
nothing unordinary happened during the update as far as I know. But the user hoseasanga experienced the same problem after that update. We are both using the same phone (HUAWEI Y6PRO).
It was also weird, that for the site "Mapogoro @ Kibaoni" in the same organiation, measurements were still available after the update.

Best regards,
Timo
