### ISSUE TITLE
data disorder when exported

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#46]
Dear all,
when exporting data from discharge.ch for the site "Mswiswi river @ Chang'ombe intake (Mswiswi Irrigation Committee)" in the organisation "Rufiji Basin" I found that data is not ordered correctly. Please see below:

![screenshot 27 03 17](https://cloud.githubusercontent.com/assets/25477472/24348204/2ed508ea-12db-11e7-97bb-78903b387df0.jpg)

![screenshot 27 03 17 2](https://cloud.githubusercontent.com/assets/25477472/24348207/313cc488-12db-11e7-9eb8-f9767dbbf4fb.png)

**Comment by timoherberz** [comment]
This also occurs for the sites: "Mswiswi river @ Kongolo intake" & "Ndembera @ Mamcos"

**Comment by bosnjak** [comment]
Hi @timoherberz, thanks for reporting. We will change this and it will be available in the next release. Will update you.

**Comment by bosnjak** [comment]
Hi @timoherberz, this was fixed, can you please check and close if everything is ok?

**Comment by timoherberz** [comment]
Checked and ok!
