### ISSUE TITLE
Multiple measurements uploaded to discharge.ch

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#48]
Dear all,
as you can see on the screenshot, one measurement is uploaded several times and appears as multiple measurements on discharge.ch. The screenshot was taken for the site "Ipatagwa River @ Ipatagwa intake" in the organisation "Rufiji Basin", but this issue also occurs with other sites in the same organisation.

![screenshot 03 04 17](https://cloud.githubusercontent.com/assets/25477472/24600091/6249da5c-1853-11e7-86b8-359a924c073d.png)

Regards, Timo

**Comment by rmunk** [comment]
Dear Timo,

can you pleas give a little more details about this issue. How was the connection when you sent the measurement? Did you just press upload button once or did you try to upload multiple times? Were there any errors reported while trying to upload?

Thanks,
Ranko

**Comment by timoherberz** [comment]
Dear Ranko,

I am sorry, but I cannot give you much more details. Omary is one of our crowd-senders in Tanzania and I am already back in Switzerland. 
I can guess, that network was rather bad when the data was sent. Maybe the issue is comparable to the already closed "Multiple sites created"-issue, which also happened more often, when network was bad.
I can also guess, that Omary tried to upload multiple times, since after the first upload he got the message, that the upload did not succeed. As long as there is no tick, he must have tried to upload again and again. But as we see, the upload already worked much earlier.
I hope I could clearify things a little bit.

Best,
Timo

**Comment by bosnjak** [comment]
I guess we can close this as it didn't happen anymore?
