### ISSUE TITLE
Discharge.ch: Map zoom

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#49]
Dear all,
sometimes two sites are very close together, e.g. if one is the intake and the other one is the river site. Nevertheless they should be distinguishable from each other, when using the map. I experienced this, when using the highest zoom. When I click on the "2" nothing happens. The site is in the organisation "Themi catchment/Seliani River". I am using Google Chrome.

Best regards,
Timo

![discharge ch screenshot 18 04 17](https://cloud.githubusercontent.com/assets/25477472/25134301/8718f3c4-244f-11e7-9b54-96da5b03d054.png)

**Comment by salpeha** [comment]
Did you try to disable marker clustering? You can do that on the "map settings", the icon on lower left of the map

**Comment by timoherberz** [comment]
I just tried and it works. My bad, sorry!
