### ISSUE TITLE
Manual Wiki

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#5]
I'm not sure if I understand the second part of this this sentence from the Wiki correctly:
->Can you see the shore on both sides of the river/canal can it be approximated as a planar surface.<-
Does it mean the shore on both sides of the river/canal should be straight and span a plane?
Thanks
robert

**Comment by luethi** [comment]
yes, at leasst to a good approximation. At the end of the day, that is what the app will assume. Formally speaking: for the app all d(.)/dx =0.
I let you close this ticket, if the answer satisfies you

**Comment by bosnjak** [comment]
@naroberto if there's nothing more to add here, please close this ticket. Thanks!
