### ISSUE TITLE
Collapsed Markers disappearing at highest zoom level in Google Maps

### ISSUE THREAD

**Issue by tobiassiegfried** [luethi/Discharge_Optical_Measurement#50]
Try with upstream Seliani sites in Tanzania. When I zoom into the highest detail to separate intakes from river sites and click on the collapsed markers, the collapsed marker disappears altogether..

**Comment by bosnjak** [comment]
Hi @tobiassiegfried, I'm not sure how to reproduce it - I've tried what you described but with no luck.
Can you let me know the organization name and the exact steps?

**Comment by bosnjak** [comment]
This hasn't been reproduced in a long time, closing.
