### ISSUE TITLE
Changed existing site coordinates - now site (no data yet) fails to load properly when clicking on google maps...

### ISSUE THREAD

**Issue by tobiassiegfried** [luethi/Discharge_Optical_Measurement#51]
... though the site can still be accessed and edited when selecting it from the list of 'Sites'. As errors, Get 'Error rating curve measurements' and 'Error getting measurements'. Check yourself with 'Munghusi River Site'.

**Comment by bosnjak** [comment]
@tobiassiegfried I believe this has been fixed, I don't reproduce it anymore. Can you please confirm?
