### ISSUE TITLE
Arrows pointing in the exact opposite direction of flow after analysis (all else correct)

### ISSUE THREAD

**Issue by tobiassiegfried** [luethi/Discharge_Optical_Measurement#52]
I am analysing in detail the collected data in Mubuku Scheme, Uganda.

While looking at the site 'Main Canal P2' it has come to my attention that in 10 out of 40 valid measurements, the arrows drawn on the images taken by the crowd sender are pointing in the opposite direction of flow. All else seems to be correct. 

I do not know if this is simply a 'drawing the arrows' issue or if this is pointing to a bigger underlying issue. It appears elsewhere in Mubuku scheme. it seems to only appear in high velocity conditions. whatever the reason, we should dig deeper here!

for your convenience, I had downloaded all data available from the site and marked those affected in the issue column of the attached Excel Sheet with arrows - see All Data Sheet!

[Main_Canal_P2.xlsx](https://github.com/luethi/Discharge_Optical_Measurement/files/1128471/Main_Canal_P2.xlsx)

**Comment by bosnjak** [comment]
@luethi this is an old ticket, but still can benefit from your feedback as this is on the lib side of things?
