### ISSUE TITLE
not issue, but suggestion for usability improvement

### ISSUE THREAD

**Issue by tobiassiegfried** [luethi/Discharge_Optical_Measurement#53]
Suggestion for usability improvement of website

1) when in the full screen view of measurements, use the down/up arrow to access the next/previous measurement and the left/right arrow to switch between the measurement pages (10 are always shown). sort of like navigating an image collection on Facebook or videos on VIMEO.

2) allow for filtering 'is equal to' and not just greater than our lesser than

**Comment by bosnjak** [comment]
Usable feedback, thanks @tobiassiegfried. I've created the ticket on our backlog, you can track it here: https://github.com/luethi/discharge_web_frontend/issues/474
