### ISSUE TITLE
Measurement (Video vs Picture)

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#6]
When performing a measurement, the application always takes a video (even for fully calibrated sites like Letten). Should there not be the possibility of taking only a picture?

**Comment by luethi** [comment]
hi Phanos,
we also just touched this point. The feature will come, together with an imporved collect menu

**Comment by phanosh** [comment]
Nice!
Do we roughly know when the updated version will be available?

**Comment by luethi** [comment]
it will be after the so-called production, which is full google release
