### ISSUE TITLE
Setting up a free profile

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#8]
For setting up a free profile, the web-platform has to be used, but we can't see how to input the data. Currently the "Free profile Parameter" window only has one line. We would like to go test the discharge app but we don't know in which format to capture the cross-section of the channel.

**Comment by salpeha** [comment]
As you mentioned, the values have to be introduced in the "Free profile Parameter" window. In that one line you have to write the profile like this: y1,y2,..,yn,z1,z2,..zn. If the format is correct the "update" button becomes active.
