### ISSUE TITLE
Looking at profile on smartphone

### ISSUE THREAD

**Issue by naroberto** [luethi/Discharge_Optical_Measurement#9]
Dear all,
We have a little issue with the profile geometry shown on the smartphone. 
When we type in the coordinates with y0,z0 in middle of the canal the profile is not visible on the phone anymore... 

![screenshot_2016-09-13-09-15-04](https://cloud.githubusercontent.com/assets/21307977/18465052/f479119e-7994-11e6-81ed-e52378b01b09.png)

**Comment by luethi** [comment]
og yes, I redirect this issue to Ranko

**Comment by salpeha** [comment]
![screenshot_2016-09-13-09-58-57](https://cloud.githubusercontent.com/assets/14312570/18465835/29bda370-7999-11e6-8c72-b1a58e6b83f9.png)
Hi Robert, can you take a look now and let me now if it works like that? Of course you have to set-up the markers reference system accordingly.
I changed the reference system, you set it as it would be a not free profile. The reference system Thomas mentioned is only for defined cross sections.

**Comment by luethi** [comment]
Its true, we can easily avoid this bug, by making sure all y-values are positive. I close the ticket.
